import NavbarPage from "components/navigations/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import WagmiProviders from "providers/WagmiProviders";
import FooterPage from "components/navigations/footer";
import ApolloProviders from "providers/ApolloProviders";

export const metadata = {
  title: "Quick Raven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bgTop = "rgba(116, 27, 229, 0.24) 0%, rgba(116, 27, 229, 0) 100%";
  const bgBottom = " rgba(239, 200, 28, 0.12) 0%, rgba(239, 200, 28, 0) 100%";
  const bgSolid = "#08020F";

  return (
    <html lang="en">
      <head>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="viewport" content="width=device-width, user-scalable=no" />
      </head>
      <body
        style={{
          background: `radial-gradient(69.44% 97.65% at 50% 13.23%, ${bgTop}), radial-gradient(47.12% 66.26% at 50% 97.85%, ${bgBottom}), ${bgSolid};`,
        }}
      >
        <WagmiProviders>
          <ApolloProviders>
            <NavbarPage />
            {children}
            <FooterPage />
          </ApolloProviders>
        </WagmiProviders>
      </body>
    </html>
  );
}
